sudo: required
language:
  - objective-c
before_install:
  # TavisCI's OSX environment gives us node 0.10.32
  # Use NVM to update it to 0.12
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install 0.12
before_script:
  - npm install
  - npm install -g gulp
script:
  - npm test
after_success:
  - /Users/travis/build/appium/appium-ios-driver/node_modules/appium-gulp-plugins/node_modules/.bin/babel-node /Users/travis/build/appium/appium-ios-driver/node_modules/appium-gulp-plugins/node_modules/.bin/isparta cover --dir coverage /Users/travis/build/appium/appium-ios-driver/node_modules/appium-gulp-plugins/node_modules/.bin/_mocha -- --require /Users/travis/build/appium/appium-ios-driver/node_modules/appium-gulp-plugins/lib/../babelhook --reporter dot ./test/capability-specs.js ./test/commands/logging-e2e-specs.js ./test/driver-specs.js
